"""ULQF metric catalog — subset implemented for deterministic evaluation."""

from __future__ import annotations

from .models import MetricDefinition, QualityDimension

# Metrics we compute today from extraction.json (+ optional run metadata).
IMPLEMENTED_METRICS: dict[str, MetricDefinition] = {
    # ── Section 1: Provenance ──────────────────────────────────────────────
    "P-03": MetricDefinition(
        metric_id="P-03",
        name="extractor_model",
        dimension=QualityDimension.provenance,
        description="Model used for extraction",
        unit=None,
        higher_is_better=False,
    ),
    "P-09": MetricDefinition(
        metric_id="P-09",
        name="textbook_title",
        dimension=QualityDimension.provenance,
        description="Source textbook",
    ),
    "P-10": MetricDefinition(
        metric_id="P-10",
        name="subject",
        dimension=QualityDimension.provenance,
        description="Subject domain",
    ),
    "P-11": MetricDefinition(
        metric_id="P-11",
        name="chapters_in_run",
        dimension=QualityDimension.provenance,
        description="Chapters processed",
        unit="count",
    ),
    "P-13": MetricDefinition(
        metric_id="P-13",
        name="skipped_phases",
        dimension=QualityDimension.provenance,
        description="Pipeline phases skipped",
        unit="count",
        higher_is_better=False,
    ),
    "P-14": MetricDefinition(
        metric_id="P-14",
        name="total_elapsed_seconds",
        dimension=QualityDimension.provenance,
        description="Total generation time",
        unit="seconds",
        higher_is_better=False,
    ),
    # ── Section 2: Curriculum extraction ───────────────────────────────────
    "CE-01": MetricDefinition(
        metric_id="CE-01",
        name="topics_count",
        dimension=QualityDimension.curriculum_extraction,
        description="Total extracted topics",
        unit="count",
    ),
    "CE-02": MetricDefinition(
        metric_id="CE-02",
        name="diagrams_count",
        dimension=QualityDimension.curriculum_extraction,
        description="Total extracted diagrams",
        unit="count",
    ),
    "CE-03": MetricDefinition(
        metric_id="CE-03",
        name="questions_count",
        dimension=QualityDimension.curriculum_extraction,
        description="Total extracted questions",
        unit="count",
    ),
    "CE-05": MetricDefinition(
        metric_id="CE-05",
        name="duplicate_id_count",
        dimension=QualityDimension.curriculum_extraction,
        description="Duplicate topic identifiers",
        unit="count",
        higher_is_better=False,
    ),
    "CE-06": MetricDefinition(
        metric_id="CE-06",
        name="dangling_reference_count",
        dimension=QualityDimension.curriculum_extraction,
        description="Prereq links to missing topics",
        unit="count",
        higher_is_better=False,
    ),
    "CE-07": MetricDefinition(
        metric_id="CE-07",
        name="prereq_cycle_count",
        dimension=QualityDimension.curriculum_extraction,
        description="Cycles in prerequisite graph",
        unit="count",
        higher_is_better=False,
    ),
    "CE-08": MetricDefinition(
        metric_id="CE-08",
        name="empty_understanding_count",
        dimension=QualityDimension.curriculum_extraction,
        description="Topics lacking explanations",
        unit="count",
        higher_is_better=False,
    ),
    "CE-12": MetricDefinition(
        metric_id="CE-12",
        name="topic_needs_review_rate",
        dimension=QualityDimension.curriculum_extraction,
        description="Topics flagged for review",
        unit="percent",
        higher_is_better=False,
    ),
    "CE-15": MetricDefinition(
        metric_id="CE-15",
        name="embedding_coverage_pct",
        dimension=QualityDimension.curriculum_extraction,
        description="Topics with embeddings",
        unit="percent",
    ),
    "CE-16": MetricDefinition(
        metric_id="CE-16",
        name="prereq_link_density",
        dimension=QualityDimension.curriculum_extraction,
        description="Average prerequisite links per topic",
        unit="ratio",
    ),
    "CE-17": MetricDefinition(
        metric_id="CE-17",
        name="book_examples_per_topic",
        dimension=QualityDimension.curriculum_extraction,
        description="Book examples per topic",
        unit="ratio",
    ),
    "CE-18": MetricDefinition(
        metric_id="CE-18",
        name="orig_content_length_chars",
        dimension=QualityDimension.curriculum_extraction,
        description="Original content size",
        unit="chars",
    ),
    "CE-19": MetricDefinition(
        metric_id="CE-19",
        name="understanding_length_chars",
        dimension=QualityDimension.curriculum_extraction,
        description="Generated understanding size",
        unit="chars",
    ),
    "CE-09": MetricDefinition(
        metric_id="CE-09",
        name="semantic_flagged_rate",
        dimension=QualityDimension.curriculum_extraction,
        description="Semantic validation topics flagged",
        unit="percent",
        higher_is_better=False,
    ),
    "CE-13": MetricDefinition(
        metric_id="CE-13",
        name="diagram_render_fail_rate",
        dimension=QualityDimension.curriculum_extraction,
        description="Diagram render failures in validation gate",
        unit="percent",
        higher_is_better=False,
    ),
    "CE-14": MetricDefinition(
        metric_id="CE-14",
        name="semantic_wrong_count",
        dimension=QualityDimension.curriculum_extraction,
        description="SEMANTIC_WRONG issues from validation",
        unit="count",
        higher_is_better=False,
    ),
    # ── Section 3: Chapter arc ─────────────────────────────────────────────
    "CA-01": MetricDefinition(
        metric_id="CA-01",
        name="concept_sequence_length",
        dimension=QualityDimension.chapter_arc,
        description="Concepts in chapter learning sequence",
        unit="count",
    ),
    "CA-03": MetricDefinition(
        metric_id="CA-03",
        name="chapter_has_lecture_plan",
        dimension=QualityDimension.chapter_arc,
        description="Chapter lecture plan exists",
        unit="boolean",
    ),
    "CA-05": MetricDefinition(
        metric_id="CA-05",
        name="topics_in_chapter_vs_planned",
        dimension=QualityDimension.chapter_arc,
        description="Actual topics ÷ chapter topic_ids",
        unit="ratio",
    ),
    # ── Section 4: Lesson plan (structural) ────────────────────────────────
    "LP-01": MetricDefinition(
        metric_id="LP-01",
        name="lesson_plan_present_rate",
        dimension=QualityDimension.lesson_plan,
        description="Topics with a lesson plan",
        unit="percent",
    ),
    "LP-02": MetricDefinition(
        metric_id="LP-02",
        name="hook_opener_forbidden_count",
        dimension=QualityDimension.lesson_plan,
        description="Hooks using prohibited openers",
        unit="count",
        higher_is_better=False,
    ),
    "LP-04": MetricDefinition(
        metric_id="LP-04",
        name="hook_text_length_chars_avg",
        dimension=QualityDimension.lesson_plan,
        description="Average hook length",
        unit="chars",
    ),
    "LP-06": MetricDefinition(
        metric_id="LP-06",
        name="crucial_facts_count_avg",
        dimension=QualityDimension.lesson_plan,
        description="Average crucial facts per plan",
        unit="count",
    ),
    "LP-08": MetricDefinition(
        metric_id="LP-08",
        name="crucial_facts_all_pressed_twice_rate",
        dimension=QualityDimension.lesson_plan,
        description="Plans with all crucial facts pressed twice",
        unit="percent",
    ),
    "LP-09": MetricDefinition(
        metric_id="LP-09",
        name="diagram_count_avg",
        dimension=QualityDimension.lesson_plan,
        description="Average diagrams per lesson plan",
        unit="count",
    ),
    "LP-10": MetricDefinition(
        metric_id="LP-10",
        name="diagram_count_over_cap",
        dimension=QualityDimension.lesson_plan,
        description="Plans exceeding diagram cap (>2)",
        unit="count",
        higher_is_better=False,
    ),
    "LP-13": MetricDefinition(
        metric_id="LP-13",
        name="choreography_step_count_avg",
        dimension=QualityDimension.lesson_plan,
        description="Average choreography steps per plan",
        unit="count",
    ),
    "LP-16": MetricDefinition(
        metric_id="LP-16",
        name="question_payoff_pair_present_rate",
        dimension=QualityDimension.lesson_plan,
        description="Plans with question + payoff steps",
        unit="percent",
    ),
    "LP-17": MetricDefinition(
        metric_id="LP-17",
        name="question_payoff_distance_steps_avg",
        dimension=QualityDimension.lesson_plan,
        description="Avg steps between question and payoff",
        unit="steps",
        higher_is_better=False,
    ),
    "LP-20": MetricDefinition(
        metric_id="LP-20",
        name="equations_count_total",
        dimension=QualityDimension.lesson_plan,
        description="Equations introduced across plans",
        unit="count",
    ),
    "LP-21": MetricDefinition(
        metric_id="LP-21",
        name="equation_motivation_present_rate",
        dimension=QualityDimension.lesson_plan,
        description="Equations with plain-language motivation",
        unit="percent",
    ),
    "LP-22": MetricDefinition(
        metric_id="LP-22",
        name="presentation_mode_build_up_count",
        dimension=QualityDimension.lesson_plan,
        description="Diagrams using build_up presentation",
        unit="count",
    ),
    "LP-30": MetricDefinition(
        metric_id="LP-30",
        name="plan_judge_avg_score",
        dimension=QualityDimension.lesson_plan,
        description="Average PlanJudge score (1–5)",
        unit="score",
    ),
    "LP-31": MetricDefinition(
        metric_id="LP-31",
        name="plan_judge_pass_rate",
        dimension=QualityDimension.lesson_plan,
        description="Plans passing PlanJudge threshold",
        unit="percent",
    ),
    "LP-32": MetricDefinition(
        metric_id="LP-32",
        name="plan_regen_attempts_avg",
        dimension=QualityDimension.lesson_plan,
        description="Average plan regeneration attempts per topic",
        unit="count",
        higher_is_better=False,
    ),
    "DG-34": MetricDefinition(
        metric_id="DG-34",
        name="diagram_qa_avg_score",
        dimension=QualityDimension.layout,
        description="Average DiagramQA vision score (1–5)",
        unit="score",
    ),
    "DG-35": MetricDefinition(
        metric_id="DG-35",
        name="diagram_qa_pass_rate",
        dimension=QualityDimension.layout,
        description="Diagrams passing DiagramQA threshold",
        unit="percent",
    ),
    # ── Section 6: Narration ───────────────────────────────────────────────
    "NR-48": MetricDefinition(
        metric_id="NR-48",
        name="narration_redundancy_rate",
        dimension=QualityDimension.narration,
        description="Duplicate sentences in narration",
        unit="percent",
        higher_is_better=False,
    ),
    "NR-49": MetricDefinition(
        metric_id="NR-49",
        name="narration_words_per_topic_avg",
        dimension=QualityDimension.narration,
        description="Average narration words per topic",
        unit="words",
    ),
    "NR-clarity": MetricDefinition(
        metric_id="NR-clarity",
        name="narration_clarity_score",
        dimension=QualityDimension.narration,
        description="LLM judge clarity rubric",
        unit="score",
    ),
    "NR-engagement": MetricDefinition(
        metric_id="NR-engagement",
        name="narration_engagement_score",
        dimension=QualityDimension.narration,
        description="LLM judge engagement rubric",
        unit="score",
    ),
    # ── Section 8: Layout ──────────────────────────────────────────────────
    "LY-14": MetricDefinition(
        metric_id="LY-14",
        name="notebook_fill_pct_avg",
        dimension=QualityDimension.layout,
        description="Average notebook height utilization",
        unit="percent",
    ),
    # ── Section 10: Educational (deterministic proxies) ────────────────────
    "EDU-20": MetricDefinition(
        metric_id="EDU-20",
        name="repetition_rate",
        dimension=QualityDimension.educational,
        description="Repeated sentences in chapter narration",
        unit="percent",
        higher_is_better=False,
    ),
    "EDU-51": MetricDefinition(
        metric_id="EDU-51",
        name="question_frequency_per_plan",
        dimension=QualityDimension.educational,
        description="Question steps per lesson plan",
        unit="ratio",
    ),
    "EDU-52": MetricDefinition(
        metric_id="EDU-52",
        name="payoff_frequency_per_plan",
        dimension=QualityDimension.educational,
        description="Payoff steps per lesson plan",
        unit="ratio",
    ),
    "EDU-60": MetricDefinition(
        metric_id="EDU-60",
        name="reinforcement_count_total",
        dimension=QualityDimension.educational,
        description="Crucial-fact reinforcement steps",
        unit="count",
    ),
    "EDU-62": MetricDefinition(
        metric_id="EDU-62",
        name="assembled_script_present",
        dimension=QualityDimension.educational,
        description="Chapter has assembled script",
        unit="boolean",
    ),
    "EDU-domain-fit": MetricDefinition(
        metric_id="EDU-domain-fit",
        name="domain_fit_score",
        dimension=QualityDimension.educational,
        description="Narration sounds native to subject",
        unit="score",
    ),
    "EDU-analogy-leakage": MetricDefinition(
        metric_id="EDU-analogy-leakage",
        name="analogy_leakage_score",
        dimension=QualityDimension.educational,
        description="Wrong-domain metaphor severity (inverted for index)",
        unit="score",
        higher_is_better=False,
    ),
    "EDU-factual-grounding": MetricDefinition(
        metric_id="EDU-factual-grounding",
        name="factual_grounding_score",
        dimension=QualityDimension.educational,
        description="Claims traceable to source excerpt",
        unit="score",
    ),
    "BE-01": MetricDefinition(
        metric_id="BE-01",
        name="book_example_coverage_pct",
        dimension=QualityDimension.assessment,
        description="Book examples woven into lesson plans",
        unit="percent",
    ),
    "BE-02": MetricDefinition(
        metric_id="BE-02",
        name="book_coverage_gap_count",
        dimension=QualityDimension.assessment,
        description="Uncovered book examples",
        unit="count",
        higher_is_better=False,
    ),
    "CO-10": MetricDefinition(
        metric_id="CO-10",
        name="quality_per_minute",
        dimension=QualityDimension.provenance,
        description="LES per pipeline minute",
        unit="score_per_min",
    ),
    # ── Composite ──────────────────────────────────────────────────────────
    "LES": MetricDefinition(
        metric_id="LES",
        name="lecture_excellence_score",
        dimension=QualityDimension.composite,
        description="Weighted composite (TQI/EQI/LEI)",
        unit="score",
    ),
    "TQI": MetricDefinition(
        metric_id="TQI",
        name="technical_quality_index",
        dimension=QualityDimension.composite,
        description="Technical Quality Index",
        unit="score",
    ),
    "EQI": MetricDefinition(
        metric_id="EQI",
        name="educational_quality_index",
        dimension=QualityDimension.composite,
        description="Educational Quality Index",
        unit="score",
    ),
    "LEI": MetricDefinition(
        metric_id="LEI",
        name="learning_effectiveness_index",
        dimension=QualityDimension.composite,
        description="Learning Effectiveness Index",
        unit="score",
    ),
}


def definition(metric_id: str) -> MetricDefinition:
    if metric_id not in IMPLEMENTED_METRICS:
        raise KeyError(f"Unknown ULQF metric: {metric_id}")
    return IMPLEMENTED_METRICS[metric_id]
